# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Initialize an array of doubles in parallel
#'
#' Initialize an array (sin function) in parallel.
#'
#' @param size size of array
#'
#' @export
table_multiple_threads <- function(size) {
    .Call('_RcppOMP_table_multiple_threads', PACKAGE = 'RcppOMP', size)
}

#' Initialize an array of doubles with SIMD (single thread; vectorized)
#'
#' Initialize an array (sin function) with SIMD. Please note this probably won't
#' be any faster than serial without a parallel floating point library (AMD and Intel have some).
#'
#' @param size size of array
#'
#' @export
table_simd <- function(size) {
    .Call('_RcppOMP_table_simd', PACKAGE = 'RcppOMP', size)
}

#' Initialize an array of doubles in serial
#'
#' Initialize an array (sin function) in serial. This is for comparison purposes.
#'
#' @param size size of array
#'
#' @export
#' @export
table_serial <- function(size) {
    .Call('_RcppOMP_table_serial', PACKAGE = 'RcppOMP', size)
}

#' Calculate and display Mandelbrot fractal
#'
#' See the title; uses ordered dynamic scheduling for parallelism.
#'
#' @param width resolution
#' @param height resolution
#'
#' @export
mandelbrot <- function(width = 78L, height = 44L) {
    invisible(.Call('_RcppOMP_mandelbrot', PACKAGE = 'RcppOMP', width, height))
}

#' @export
rcpp_hello_world <- function() {
    .Call('_RcppOMP_rcpp_hello_world', PACKAGE = 'RcppOMP')
}

#' @export
rcpp_hello_world_omp <- function() {
    invisible(.Call('_RcppOMP_rcpp_hello_world_omp', PACKAGE = 'RcppOMP'))
}

#' @export
rcpp_hello_world_omp_2 <- function() {
    invisible(.Call('_RcppOMP_rcpp_hello_world_omp_2', PACKAGE = 'RcppOMP'))
}

#' @export
test_singletonOMP <- function(seed) {
    .Call('_RcppOMP_test_singletonOMP', PACKAGE = 'RcppOMP', seed)
}

