# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_hello_world <- function() {
    .Call('_RcppOMP_rcpp_hello_world', PACKAGE = 'RcppOMP')
}

#' @export
rcpp_hello_world_omp <- function() {
    invisible(.Call('_RcppOMP_rcpp_hello_world_omp', PACKAGE = 'RcppOMP'))
}

